# Generated by Django 3.2.4 on 2021-08-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0002_leaderboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
